
== SOCRATES

=== Easing the use of Asciidoctor to produce manuscripts.

Socrates is a front-end CLI written in Go for creating and compiling manuscripts from sets of asciidoc files. Socrates is written in Go so it produces a single executable file with no dependencies, making it easy to install and update.

Asciidoctor is a well-designed language for producing rich and complicated manuscripts. Socrates eases the use of Asciidoctor by providing a front-end to Asciidoctor that eases and speeds up development of a manuscript. 

Socrates assists in setting up a manuscript project with a default structure, adding new manuscript elements, and compiling those files into a final manuscript in PDF or HTML format.

Best of all, every file needed to construct a manuscript is entirely text, which means it can be easily versioned in Git!

=== Getting Started

To get started, visit the https://socratesdocs.netlify.com[Socrates Documentation] page. 

=== Roadmap

* Further documentation
* More PDF and HTML styles.
* Switch to produce a chapters-only manuscript _master.adoc_ file, e.g., --chapters-only
