:source-highlighter: rouge

Socrates is a front-end CLI written in Go for creating manuscripts from asciidoc files. It uses the Asciidoctor tool-chain to create manuscript from a set of files. Socrates is written in Go so it produces a single executable file with no dependencies, making it easy to install and update.

== Prerequisites

Socrates relies on these additional tools.

=== Ruby and Gems

Socrates requires a working Ruby installation and the following gems:

* asciidoctor
* asciidoctor-pdf
* asciidoctor-bibliography
* asciidoctor-diagram

To install Ruby, MacOS and Linux users can use their package manager. Windows users can use the packages at https://rubyinstaller.org[RubyInstaller]. Socrates has been tested with Ruby 2.5.x.

To install the needed gems:

[source,console]
----
gem install asciidoctor asciidoctor-diagram asciidoctor-bibliography
gem install asciidoctor-pdf --pre
----

=== Fonts

Fonts are used when producing PDFs using asciidoctor-pdf. Out of the box, Socrates support three fonts:

* Noto Serif (available at https://fonts.google.com/specimen/Noto+Serif?selection.family=Noto+Serif)[Google Fonts]) is the primary font.
* M+ 1nm and M+ 1p (https://github.com/rayshan/mplus-fonts[available here]) are fallback fonts.

Download the fonts and use your operating system font tool to install the fonts.

You are not required to use the default fonts. Fonts can be changed by editing the default-theme.yml file in the src/resources/pdf-styles folder.

=== Optional Fopub support

Socrates can also generate PDF files using the https://github.com/asciidoctor/asciidoctor-fopub[asciidoctor-fopub] tool-chain. See the asciidoctor-fopub github repository for instructions on installing the tool-chain. 

Once installed, make sure the fopub executable is in your path statement so that Socrates can find the tool-chain.

== Installation

=== Binary Installation

Note: The instructions below install the 64 bit build. 32 bit builds are also available from the release page.

==== GNU/Linux

[source,console]
----
wget https://github.com/rpwatkins/socrates/releases/download/v0.0.1/socrates_0.0.2_linux_amd64.tar.gz
tar -xvzf socrates_0.0.2_linux_amd64.tar.gz
sudo mv socrates /usr/local/bin/socrates
----

==== MacOS

[source,console]
----
curl -OL https://github.com/rpwatkins/rpwatkins/releases/download/v0.0.1/socrates_0.0.2_darwin_amd64.tar.gz
tar -xvzf socrates_0.0.2_darwin_amd64.tar.gz
sudo mv socrates /usr/local/bin/socrates
# or if you have ~/bin folder setup in the environment PATH variable
mv buffalo ~/bin/socrates
----

==== Windows

Download the windows release from the Releases page, extract the socrates.exe file, and place the socrates executable somewhere on your path.

=== Source Install

[source,console]
----
go get -u github.com/rpwatkins/socrates
----

== Zotero integration

Socrates supports references and bibliography generation using https://github.com/riboseinc/asciidoctor-bibliography[asciidoctor-bibliography]. For complete instructions on using asciidoctor-bibliography, see the its github page. Asciidoctor-bibliography relies on a bibtex file (src/references.bib) to populate manuscript references and a bibliography. Many programs can generate bibtex files.

https://www.zotero.org[Zotero], an open source reference manager, has excellent support for bibtex files when the BetterBibtex add-on is enabled. One can then use Zotero to generate and update the references.bib files. Also, when using the https://github.com/retorquere/zotero-better-bibtex[BetterBibTex] add-on, the exported references.bib is updated every time a reference is added, edited, or deleted from the Zotero database.

== Visual Studio Code

Any text editor can be used to edit manuscript files. I recommend https://code.visualstudio.com[Visual Studio Code] because it has very good support for asciidoc files. VS Code with the https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode[asciidoc extension] provides live preview, syntax highlighting, and more.

Also, if you choose to use VS Code, there is a very useful https://marketplace.visualstudio.com/items?itemName=mblode.zotero[Zotero connector] that allows placing citations directly in the editor right from VS Code.

== Using Socrates

Socrates accepts the following commands:

* init
* clean
* version
* pdf
* fopub
* html
* docbook

=== init

To create a new project, create an empty folder. Socrates will use the name of this folder to name you manuscript.
From within the new folder, initilize a new project:

[source,console]
----
socrates init
----

This will create a "src/" folder containing a master.adoc, chapters folder (and a starter chapter), the back_matter folder (with a default bibliography), and image folder to store images, an assets folder (in which any other files you may want stored with the manuscript), a resources folder that contain the asciidoctor-pdf style template for the manuscript, and a blank references.bib file.

These source files will be used to generate html pages, PDF, or docbook5 files. All built manuscripts can be found in the "builds/" folder.

=== pdf

[source,console]
----
socrates pdf
----

The pdf command creates a PDF file using asciidoctor-pdf and the included default style template.

=== html

[source,console]
----
socrates html
----

The html command creates a self-contained web page (html file). Images are inlined using the data-uri switch in asciidoctor.

=== fopub

[source,console]
----
socrates fopub
----

The fopub command creates a PDF file using the asciidoctor-fopub tool-chain.

=== docbook

[source,console]
----
socrates docbook
----

The docbook command creates a docbook5 compatible xml file.

=== clean

[source,console]
----
socrates clean
----

The clean command empties all builds in the build folder.

=== version

[source,console]
----
socrates version
----

The version command displays the current Socrates version number.

== Roadmap

* Add command to easily add a new manuscript file (chapter, section, etc) with include directive in parent
* More detailed documentation. 



